### ISSUE TITLE
Permissions: Download-all button does NOT respect shared links permissions

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-rdm-records#1168]
Package version (if known): V11

## Describe the bug
Open this [demo site record link](https://inveniordm.web.cern.ch/records/ng23f-pp895?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjU1NDUwNzdjLTRmZjgtNDI0Ny1hMDZmLTMwNDA2OTJhZDc1ZiIsImRhdGEiOnt9LCJyYW5kb20iOiI0YTYyMGQ0MTgyNjNmNTEwMzhhNjE4OTEzMDljOTJmMCJ9.3r8m5UrcH4I68l3309VXEaT7r4dI4GVfv1IcRsZqqztwMsApG02ua8ypcneUhSww0eIKC2j048SyYvsLCaieAA) 

You will notice two things:
1-  the preview  show a broken link
2- if you click "Download all" button it will download a zip file for all restricted files without any restrictions, on the other hand if you click download for a specific file it will correctlly show you a permission denied page.

## Steps to Reproduce
1. Create a restricted community
2. Publish a restricted record
3. On the record page, Click share with Can view permission and copy the generated link
4. Login with a different user and paste the link
5. Click the download all button
6. Get all the restricted files in the zip file
7. Notice the broken preview

## Expected behavior
- IIIF previewer should not show a broken link
- Download all files should show a permission denied page as the download Button

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/36583694/215604121-7bbc44e1-a4b6-46dd-863b-70a4605524ff.png)

**Comment by kpsherva** [comment]
Thank you for testing!
As you can see in the share link, the person who is given the link, should have access to the files (= can also download them), therefore it is intended behaviour:
![Screenshot 2023-01-31 at 10 54 17](https://user-images.githubusercontent.com/38131488/215727517-0aeef25f-17df-45b0-906b-c3eaa294dece.png)

The incorrect behaviour that we were able to reproduce was broken preview.

**Comment by Samk13** [comment]
Thank you for the reply,
- If this is the intended behavior, why do clicking download and download all differ in behavior (see link in the previous comment)?
Notice that the previewer is not showing the file because it's 403 (FORBIDDEN) see the console log.
Don't you think we should rephrase the info message to view and download files rather than just view in that case to make it clear for restricted records users?

**Comment by slint** [comment]
> * If this is the intended behavior, why do clicking download and download all differ in behavior (see link in the previous comment)?

Indeed the issue here is that the secret link permissions are not applied correctly for read operations on the record (see the [mismatch between `can_view` and `can_preview`](https://github.com/inveniosoftware/invenio-rdm-records/blob/513391267c78236ee3e64ae17bf969f561fa54e0/invenio_rdm_records/services/permissions.py#L52-L54)). I think this confusion came from the fact that "Preview" in this context is not about the file previewer, but "previewing a draft".

> * Notice that the previewer is not showing the file because it's 403 (FORBIDDEN) see the console log.

This is incorrect, if you have any secret link actually you should be able to download, preview, read the files. Shared link types include each other (`edit > preview > view`), so having e.g. "preview" access means you also have "view" access (which already includes read access to files).

> * Don't you think we should rephrase the info message to view and download files rather than just view in that case to make it clear for restricted records users?

In my view, if one gets "view" access e.g. to a Google Drive folder, it's implicit that they can list, view metadata, and download the folder's files. I can't also think of a use-case where one would only share "view" access to only the metadata of a record.

So in this case the phrasing is confusing because it doesn't do what it says, because there is a bug in the read permissions of files (thankfully it's "lower" permissions that expected, so it's not a security issue).

---

Next steps would be to:

- [ ] Make sure "view" secret links also provide full files-related read access (list files, get metadata, download one file, download archive)
- [ ] Make sure that
  - [ ] "preview" secret links include "view" permissions
  - [ ] "edit" secret links include "preview" and "view" permissions

**Comment by max-moser** [comment]
# Background

I've done some digging and discussed with @ppanero, here's a short summary of my findings.

## FileStorage

In Invenio-Files-REST, a `FileStorage` class already exists which acts as a "backend" implementation for how to handle (uploaded) files that are in our control.
One such implementation would be the [`PyFSFileStorage`](https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/storage/pyfs.py), another one the [S3](https://github.com/inveniosoftware/invenio-s3) implementation.
These classes deal with the implementation of file operations and imply that the files are under our control.

## Storage classes

The "new" file **storage classes** (`L`ocal/`R`emote/`F`etch) in contrast do not implement file operations, but rather denote _if the file is under our control_ (e.g. in a local PyFS, or in one of our S3 systems).
* `L`: Yes, we're in charge of the files. The files' `uri` properties could be local FS paths (e.g. with PyFS) or maybe something else.
* `R`: No, the file is hosted somewhere else. The files' `uri` properties should never be a local FS path.
* `F`: The file is hosted somewhere else, but InvenioRDM will fetch the file in a background job. After the fetching is completed, the file will have storage class `L`.

# Permissions

A bit of digging revealed that the file permissions were made a bit more fine-granular over the course of the "external storage" feature, [see here](https://github.com/inveniosoftware/invenio-records-resources/commit/fd65e834e5426a789dd91e2544bdc52ae1ec1994#diff-13fd70056deb6848af5488fc2db9e690a05806d34b2b9333218e37bc60168d4bL253).

## Code paths

The **files resource** (which provides the API logic) [calls its service's `get_content_file` function](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/resources/files/resource.py#L174) when the [`/files/<file_key>/content`](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/resources/files/config.py#L26) API endpoint is used. Said service call will [check for the `can_get_content_files`](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/files/service.py#L253) permission.

The currently configured [permission policy](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/permissions.py#L78) uses a conditional permission generator based on whether the file's storage class is local or not. My guess is that there's a slight issue here, I'll investigate further :detective:

**Comment by max-moser** [comment]
The following PR deals with (parts, if not all of) this issue: https://github.com/inveniosoftware/invenio-rdm-records/pull/1171
