### ISSUE TITLE
Serialize new custom fields

### ISSUE THREAD

**Issue by anikachurilova** [inveniosoftware/invenio-rdm-records#1231]
Support new custom fields: [journal](https://github.com/inveniosoftware/invenio-rdm-records/issues/1191), [thesis](https://github.com/inveniosoftware/invenio-rdm-records/issues/1219), [notes](https://github.com/inveniosoftware/invenio-rdm-records/issues/1217), [meeting](https://github.com/inveniosoftware/invenio-rdm-records/issues/1211), [imprint](https://github.com/inveniosoftware/invenio-rdm-records/issues/1215) in existing serializers:
- [ ] csl
- [ ] datacite
- [ ] dcat
- [ ] dublincore
- [ ] geojson
- [ ] iiif
- [ ] marcxml
- [ ] bibtex

**Comment by alejandromumo** [comment]
We have two options in the [RFC](https://github.com/inveniosoftware/rfcs/blob/master/rfcs/rdm-0064-custom-fields.md#unresolved-questions):

- Per field
- Per export format 

This topic needs a discussion before the implementation

**Comment by alejandromumo** [comment]
We decided to prototype the option `per field`, using `journal` as an example.

The prototype should also contain multiple formats to have a grasp on how this can grow in terms of code

**Comment by alejandromumo** [comment]
For the prototype, we decided to add a generic post dump pipeline (can also be implemented for other stages of the serialization, e.g. `pre_dump`). 

Each serializer then adds the steps it sees fit for its own needs (e.g. `DataciteJsonSerializer` adds custom fields processors, each defining its own `post_dump` implementation). Everything is then "merged" together (with many caveats)

**Comment by alejandromumo** [comment]
To showcase the implemented mechanism I implemented `journal` serialization into `DataCite`, `MarcXML` and `DublinCore`. Also added `DublinCore` serializartion for `meeting`. 

Since this will scale up (e.g. X formats * Y custom fields), I will first wait until the post_dump/pre_dump mechanism is fully approved before implementing all the combinations of custom fields and formats.

Thus, I am moving the issue to review
