### ISSUE TITLE
iiif: unskip and fix tests

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-rdm-records#1291]
changes introduced in https://github.com/inveniosoftware/invenio-rdm-records/pull/1271
exposed an issue with dumping `@id` key, therefore the tests had to be skipped until an underlying issue is found (https://github.com/inveniosoftware/invenio-rdm-records/pull/1271/commits/2a53743496dcb7fb34ad33608f024e9c53ec6356)

**Comment by dfdan** [comment]
I've taken a look at this - the test are failing "correctly", ie the manifests are no longer validating after #1271 was merged.

The serializer no longer recieves a file list with the links object included - these links are required by the manifest serializer to generate the @id for both the canvases and the images.

**Comment by dfdan** [comment]
Just bumping...  had a quick word with @slint. Manifest is not valid because here:

https://github.com/inveniosoftware/invenio-rdm-records/blob/ca1be162117eb112d3ff190ee3c5ab4b54ae7645/invenio_rdm_records/resources/serializers/iiif/schema.py#L119C22-L119C22

(and elsewhere) `links` is no longer availablew after #1271 was merged. I'm not sure if we should get them back (will this clog up the index) or generate them here in the serialzer?

**Comment by kpsherva** [comment]
from Lars:
> default_preview in /files but no in record
entries list vs dict
entries differences: bucket, checksum, created, file_id, status, storage class, updated, version_id, ext, links

top level links in files vs not in record
total_bytes in record not in files
so the two serializations should definitely be harmonized.......

probably what's needed is to:

Fix the service schema serialization of RDMFileRecordServiceConfig, RDMMediaFileRecordServiceConfig, RDMFileDraftServiceConfig and RDMMediaFileDraftServiceConfig......e.g. I don't think bucket, file_id, etc should be available there....also you might run into issues that when file metadata comes from the index you dont' have all the info available
Then make the service serialization us the file services link injection templates somehow......
