### ISSUE TITLE
DOIs: improve error message

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-rdm-records#1324]
>  "source" will show up if there is an issue with a specific metadata field, but not if there is a general error like incorrect credentials or a missing prefix. So I think the get is right, but the 'Missing field' text below is a bit confusing because you can get errors for reasons other than missing fields. 

One possible other improvement is the 403 error contains nothing useful in the `text`field beyond You are not authorized to access this resource. Maybe returning something like "403 Error: Check your credentials and prefix settings" would he more helpful for folks.

_Originally posted by @tmorrell in https://github.com/inveniosoftware/invenio-rdm-records/pull/1315#discussion_r1212035513_

**Comment by TLGINO** [comment]
After quite a bit of debugging I was not able to produce any error on the client-side (regarding inputting valid and invalid DOIs).
The only issue I found was regarding invalid `DATACITE_PREFIX` configurations
Which in turn yielded this error to the front-end
> Oops, something went wrong! The identifier was not reserved. Please try again. If the problem persists, contact user support..

Which is misleading as it seems to imply the error comes from PIDs (especially if you look at the actual error variable used `RESERVE_PID_FAILED`)
As this is a configuration issue, and the server stack trace clearly shows the error, it is not necessary to inform the user of the 'root' issue, and so this imprecision is deemed ok.


![image](https://github.com/inveniosoftware/invenio-rdm-records/assets/59311729/a329cd99-a1ed-4a44-ac83-541fe92805d3)


@tmorrell does the problem still persist on your side? Thx!

**Comment by tmorrell** [comment]
Ah, sorry for the confusion. My comment was specific to https://github.com/jrcastro2/invenio-rdm-records/blob/3b31fb26533e1ce2a74641c20a2bcd3aa27d056c/invenio_rdm_records/services/pids/providers/datacite.py#L117, which is for the logging that will show up in the console. I think the generic error for the UI is fine, since these are really technical errors that an admin needs to figure out.

I don't have a current master install, but here are some steps to reproduce what I'm talking about:

1. Set an incorrect password in `DATACITE_PASSWORD`
2. Try to register a DOI
3. Console shows error ```Error in  'Missing field' : 403.....```

That error is confusing because the error is because of a password problem, and has nothing to do with a missing field. The easiest fix is to redo the line to not say `Missing field`. A more optimal solution would be to specifically catch the 403 and suggest that it might be because of a password or prefix issue.

**Comment by TLGINO** [comment]
Perfect I'll give it a go then and see if the error still exists
Thx!

**Comment by TLGINO** [comment]
Update: can't seem to replicate the issue :/
not sure yet if this is a good sign or not
