### ISSUE TITLE
Deleting a draft redirects to a hardcoded URL

### ISSUE THREAD

**Issue by karkraeg** [inveniosoftware/invenio-rdm-records#1846]
In `deposit.js` the `delete_` function has the redirect URL after deleting a draft hardcoded: https://github.com/inveniosoftware/invenio-rdm-records/blob/0d313c61bda1c509c8518c1c30f8abc337e96967/invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/state/actions/deposit.js#L262

This should be read from the config value [`APP_RDM_DASHBOARD_ROUTES["uploads"]`](https://github.com/inveniosoftware/invenio-app-rdm/blob/56893c6a21e6ff58dd6732fa77ae34554c263a7b/invenio_app_rdm/config.py#L767) instead.

**Comment by karkraeg** [comment]
@zzacharo as discussed tuesday in the telecon, could you provide some insight here as to how the flask config could best be read from the `deposit.js`? Thanks! The `config` object doesn't contain it.

**Comment by zzacharo** [comment]
Hello,

I think it should be enough to inject the new variables in the form config:
- On [create](https://github.com/inveniosoftware/invenio-app-rdm/blob/88ec8b1b2572407c51d299700f9dea6dbb1dbc16/invenio_app_rdm/records_ui/views/deposits.py#L392)
- and [edit](https://github.com/inveniosoftware/invenio-app-rdm/blob/88ec8b1b2572407c51d299700f9dea6dbb1dbc16/invenio_app_rdm/records_ui/views/deposits.py#L457)

That would go down to the deposit form state [here](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositFormApp.js#L67) and then it is available in the actions because of [how we configure the redux store](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/store.js#L70)

Give it a go and let me know!

**Comment by karkraeg** [comment]
Hi @zzacharo, thanks for your help! It will be fixed with https://github.com/inveniosoftware/invenio-app-rdm/pull/2889 and https://github.com/inveniosoftware/invenio-rdm-records/pull/1859
