### ISSUE TITLE
dates: support for ranges and dates metadata

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#22]
Currently dates are specified as two fields (start + end). This comes from ES2 and makes it difficult with certain advanced range queries (e.g. intersections).

ES6.x onwards has the [range](https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html) type, which would allow this type of queries.

However, we should also take into account actual metadata from type `date`. For example, from @fenekku:

> for actual date metadata (as opposed to created and updated which are meta-metadata). We have "present day" books about "olden days" medical practices for instance.

Open discussion and possible solutions:

1) Keep the same structure and not give support to advance queries. In this case both use cases (ranges and content metadata) could be address with a structure similar to:

``` json
"dates": {
      "description": "Related dates and intervals.",
      "items": {
        "additionalProperties": false,
        "properties": {
          "description": {
            "description": "Description of the date or interval.",
            "type": "string"
          },
          "value": {
            "description": "Date value in ISO-8601 format. If interval, this is the start.",
            "type": "string"
          },
          "value_end": {
            "description": "End date value of interval.",
            "type": "string"
          },
          "type": {
            "description": "Type of date/interval: 'created', 'updated', 'content'..."
          }
        },
        "required": [
          "type", "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
```

2) Have two fields. One for ranges, using the ES6.x+ range type, and one for dates metadata. This might require the creation of some sort of query parsing.
3) One of the two should be added as *custom* field.

**Comment by fenekku** [comment]
Thinking about this, there are *alot* of way to encode what we want in this field.

```
"dates": {
      "description": "Related dates and intervals.",
      "type": "object",
      "properties": {
          "intervals" : {
              "type": "array"
              ...
          }
         "dates": {
             "type": "array"
         }
}
```

or as initial comment with variation of fields or only using `date` type and `range` queries but no `range` type or the reverse ...

**Comment by lnielsen** [comment]
1. Why are intersections not supported by the current method? (just asking because I'm curious)

2. Couldn't this just be done at indexing time and stay with the model as is?

3. Another thing is support [EDTF](https://www.loc.gov/standards/datetime/) for unspecific ranges.

**Comment by fenekku** [comment]
Quick thoughts. I will ponder this more later:

1- Using elasticsearch `range` type, allows us to do range queries: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html which deal with intersections and such for us. That's the main appeal. Maybe it is already possible though with some work on our end.  

2- Probably could be done at indexing time, but I think we want to keep the schema and the mapping as close as possible. So if the schema is setup properly in the first place, there isn't as much need for indexing mechanics. IMHO this is something very important: we want to keep ES mapping and jsonschema as aligned as possible because otherwise we get into the issues @lnielsen mentioned about developers choosing different fields and there being a lack of transparency about what fields are even there. (which these metadata issues are all about making clear). 

3-  The EDTF concern was in part because of size concerns in the past. EDTF will take more memory. Not much one may think, but at scale it could have an impact. IMHO, I am not genuinely concerned by that, but because field names had been chosen based on length in the past I believe (`sys` versus `internal` or `record_id` vs `recid`) the same concerns were raised here.
