### ISSUE TITLE
es: use `geo_point` and related types for geometries

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#265]
## Is your feature request related to a problem? Please describe.
Currently the `coordinates` property of the `locations` field only accepts `floats` (or an array of those).

## Describe the solution you'd like
It would be nice to take advantage of Elasticsearch's [`geo_point`](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html) and [`geo_shape`](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html). Among others to facilitate bounding box searches.

Take into account possible restrictions that might need to be documented. For example:

>Please note that string geo-points are ordered as lat,lon, while array geo-points are ordered as the reverse: lon,lat.
> Originally, lat,lon was used for both array and string, but the array format was changed early on to conform to the format used by GeoJSON.

The idea is to create a `Dumper` that is able to distinguish the shape and dump it in the correct ES field (this would require changes to the mapping). This dumper should take care also of serializing it back (i.e. for searches).

**Comment by lnielsen** [comment]
- Change the ES mappings to be able to index correctly the coordinates
- Record.dumps()/Records.loads() should be idempotent. If needed a Elasticsearch dumper extension can be written see: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/api.py#L40-L41

**Comment by alexsdutton** [comment]
There are three approaches we could take to integrating GeoJSON, with each being a different dividing line between the GeoJSON schema and the InvenioRDM schema:

* `record['metadata']['locations']` can be a GeoJSON `FeatureCollection`
* `record['metadata']['locations']` can be an array of GeoJSON `Feature`s
* `record['metadata']['locations']` can be an array of objects each with a GeoJSON geometry as their `geometry` attribute

`Feature`s can have a null geometry, so we can still support only-text locations with all three.

In the first two cases, the InvenioRDM schema will still need to constrain the GeoJSON elements to handle identifiers, place and description, which I'd propose is done with [GeoJSON foreign members](https://tools.ietf.org/html/rfc7946#section-6.1) instead of entries in the GeoJSON `properties`. This means we won't clash with anyone importing existing GeoJSON records who have their own properties, though does allow people to include arbitrary metadata within their GeoJSON, which may not be desirable.

`FeatureCollection`s can't contain other `FeatureCollection`s, so the first option is safe from arbitrary nesting.

To begin with we could enforce the type of all geometries to be Point, assuming we can easily migrate from geo_point to geo_shape in ES later. Or we could calculate the centroid ourselves using shapely, and index that separately as a geo_point.

I'd say the FeatureCollection approach is more elegant and has better reuse, but that the geometry-only approach is far more tightly constrained and loses nothing for our purposes. The Feature approach gains a bit of terseness, but is less elegant and is no more constrained than using FeatureCollections, so wins on neither metric.

**Comment by lnielsen** [comment]
### External JSON

I guess the most future proof solution is to imitate a ``FeatureCollection`` using foreign members. Thus on the REST API we would serve something like:

```json
{
    "locations": {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [6.05, 46.23333]
            },
            "identifiers": {
                "geonames": "2661235",
                "tgn": "http://vocab.getty.edu/tgn/8703679"
            },
            "place": "CERN",
            "description": "Invenio birth place."
        }]
    }
}
```

This means we could later add the bound box ``bbox`` for instance or other foreign members to the feature collection.
Also using foreign member, could allow for user specified metadata in the ``properties`` field as mention.

### Internal JSON

Internally, I would, however, remove the ``type`` key for FeatureColleciton and Feature so that internally we would store:

```json
{
    "locations": {
        "features": [{
            "geometry": {
                "type": "Point",
                "coordinates": [6.05, 46.23333]
            },
            "identifiers": {
                "geonames": "2661235",
                "tgn": "http://vocab.getty.edu/tgn/8703679"
            },
            "place": "CERN",
            "description": "Invenio birth place."
        }]
    }
}
```

Both ``"type": "FeatureCollection",``  and ``"type": "Feature"`` can easily be added via serializer as they are just constants and just increase the data size of the JSON document.

### DataCite compatibility

I think the above structure is compatible with DataCite.

### Initial implementation

As a first initial implementation, I would go with only support for ``"type": "Point"`` geometries, so that indexing becomes simple. Then later, once we know use cases a bit better, we can extend with other types.

**Comment by lnielsen** [comment]
Comments from GEO: https://geosecretariatgeneva-my.sharepoint.com/:w:/g/personal/ffranziskakis_geosecretariatgeneva_onmicrosoft_com/EbBAaAFJ7G5ElWL7RHdJZ6gBpGN9prlk94DRX8XBSkH1kg?e=cKuO8X

**Comment by alexsdutton** [comment]
That seems reasonable to me :-)

**Comment by alexsdutton** [comment]
Should we rename `place` on locations to `title`, for consistency with the rest of our schema?
