### ISSUE TITLE
records: create DOI/datacite provider

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#508]
Every PID type should have its provider class implementing a common interface. One already exists in [Invenio-PIDStore](), but it might require some changes to make it more re-usable/generic. @ntarocco started the works towards a new Provide API [here](https://github.com/inveniosoftware/invenio-rdm-records/pull/491/files).

For now we should focus on DataCite DOI, without loosing the generic idea.

**Inmediate needs:**

**PIDStore level**
- Query PIDStore to **reserve** a DOI.
- Query PIDStore to **unregister** a DOI. The question about PIDs TTLs already rose in discussions. How should we proceed with respect to it? --> No point on doing that, since it will never be used anyway and we risk bothering users that forgot an unpublished draft.

**DataCite/External queries level**
- Query DataCite to register a DOI.
- Query DataCite to update a DOI (for minor metadata changes, i.e. record `edit`).

**Comment by tmorrell** [comment]
My recommendation is to reserve a doi with the REST API `draft_doi(doi)` function (for the initial reserve button on deposit form). You can then (for unpublished drafts only) unregister with `delete_doi(doi)`. This is nice because it will guarantee that the DOI is unique with DataCite as well as within Invenio.

When a record is published use `public_doi(metadata, url, doi)` to actually register the full DOI, and `update_doi(doi, metadata)` when metadata in a record is changed. There is no way to unregister a DOI once it is public.

**Comment by ntarocco** [comment]
> My recommendation is to reserve a doi with the REST API `draft_doi(doi)` function (for the initial reserve button on deposit form). You can then (for unpublished drafts only) unregister with `delete_doi(doi)`. This is nice because it will guarantee that the DOI is unique with DataCite as well as within Invenio.
> 
> When a record is published use `public_doi(metadata, url, doi)` to actually register the full DOI, and `update_doi(doi, metadata)` when metadata in a record is changed. There is no way to unregister a DOI once it is public.

Thanks @tmorrell. Actually we were planning to keep the Zenodo implementation and reserve DOIs only locally by generating it (without contacting Datacite). This is for several reasons:
1. no external HTTP calls
2. no need of any record metadata, it can be a totally empty record
3. easy to remove/delete
Do you see any drawback with this?

**Comment by tmorrell** [comment]
The only drawback is if we let individuals customize the DOI on the deposit form, and a DOI prefix has been used to register DOIs outside of the instance. Registering a draft DOI ensures that a DOI hasn't been duplicated in DataCite.

For 2, with the REST API you can reserve a DOI with no metadata. For 3, the delete is pretty straightforward (one call). 

1 is a reasonable concern. But in terms of error handling my approach works out a bit nicer. If there is an issue with the DOI, you can return the error right when the user clicks the "Reserve DOI" button. 

My approach eliminates having to return DOI errors to the user on publish, since we can make sure that the deposit form always generates metadata that will be valid for DataCite.

It really depends on whether the DOI in the deposit form for managed DOIs is editable by the user or system generated. If it's system generated, you can skip the draft call (and don't need an unregister method implemented)

**Comment by ppanero** [comment]
@tmorrell I think the user cannot choose it's DOI value for "managed" PIDs... It can "reserve" one, but not choose it's value.

Correct me if I'm wrong @ntarocco @lnielsen. Also cuz I have coded it that way, and I'd need to change it.

**Comment by ntarocco** [comment]
Yes they cannot input their own value. I think that for now we will go with reserving a local PID.

**Comment by tmorrell** [comment]
That makes sense. But then I don't think you need "Query DataCite to unregister a DOI". This is not a possible operation if you're not reserving the DOIs. 

You could add "Query DataCite to update a DOI" to manage minor metadata changes after records are published.

**Comment by ppanero** [comment]
@tmorrell you are totally right, I forgot to update the issue after to IRL chats... apologize for the inconvenience 👼 Text updated now :) Thanks!
