### ISSUE TITLE
pids: update on re-publishing and register/update via async task in DataCite provider

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-rdm-records#562]
The implementation of the DOI registration is missing:
* update DOI record metadata on DataCite when a record is updated (Published record -> Edit -> Publish)
* DataCite provider, register/update a DOI via async task: it requires some development in components/services to be able to register async tasks to be run **after** the record has been committed into the db.

**Comment by ppanero** [comment]
Idea:

- Create a function `update_pid` at service level. The update task would call it (Note that the task has been done in https://github.com/inveniosoftware/invenio-rdm-records/pull/566). 
- Problem: The record changes need to be commited. Therefore, we could hook to the `commit`. How do we distinguis if its a creation or update, since both need to be hooked to `commit` (potentially delete too).
- Enhance provider to have `remote` operations (e.g. `resgister` and `register_remote`, `update` and `update_remote`) then the service would call those.
