### ISSUE TITLE
dependencies: should not depend on invenio-communities

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#636]
Invenio-Communities is a special type of records. Is okay for it to depende on rdm-records but not viceversa.

Any content in rdm-records related to communities (e.g. CLI) should be moved to invenio-communities.

**Comment by slint** [comment]
That's correct, but originally it didn't depend on it... The reverse dependency exists because communities share some schemas/models from RDM-Records (but otherwise communities configure and initialize separately services/resources, that currently do not have any dependencies with RDM-records).

I think the issue is that communities have to be reindexed like done [here](https://github.com/inveniosoftware/invenio-rdm-records/commit/f0c8663af21a2ead4d8af2de4473859e8d7408b1), but that might be better via a `invenio communities rebuild-index` command in `invenio-communities`. This can be eventually called from `invenio-cli` as part of the upgrade command.

**Comment by ppanero** [comment]
I agree, if possible these two modules should be disentangled as much as possible... On the other hand I see communitites uses some access components and related classes from rdm-records.

Therefore, **this task is about moving the re-indexing to communities**
