### ISSUE TITLE
serialisers: datacite JSON and XML needs a full review

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#703]
Here's examples of possible current issues:

```
-  <identifier identifierType="DOI">/datacite.158m7-jk782</identifier> # <---- missing prefix
-  HTML tags in description field.
- Publisher set to default to InvenioRDM. Seems wrong and normally there's a default for the institution i think
```

**Comment by ppanero** [comment]
> -  <identifier identifierType="DOI">/datacite.158m7-jk782</identifier> # <---- missing prefix

Most likely due to lack of prefix configured in the invenio.cfg file? Tests are passing including the prefix.

> Publisher set to default to InvenioRDM. Seems wrong and normally there's a default for the institution i think

There is no default in the `services.schemas.metadata`, nor in the datacite serialization.... It is set to `InvenioRDM` demo data and the confests record fixture. We support this value from the deposit form.

> -  HTML tags in description field.

Fixed in the `_get_text` function. Using the `StrippedHTML` field from marshmallow utils.
