### ISSUE TITLE
detail page will not render if no communities

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/invenio-rdm-records#71]
similar to #69, #70 - 

side_bar.html template fails to render if the record in question is not assigned to a community (which is not required)

**Comment by fenekku** [comment]
This is a trickier one ...

The template should be able to rely on a "model" for the record that is completely filled I believe (i.e. has sane defaults for optional fields). But this "model" is **not** the *load* marshmallow schema. It should be the jsonschema or ES mapping *dumped* via the marshmallow schema. A field not marked `required=True` in the schema does not imply that this field may be absent: it might be filled by internal processes and, if not, a sane default value should be returned that the return layer knows how to deal with.   

In this context, the `community` field would be guaranteed to have a value in the template, because a default would be passed... because we want all records to be part of a community (with default being the "General" community)

But this is my take / what I will be pushing for and the current schema does not represent this yet.

**Comment by dfdan** [comment]
Okay, that makes sense - I didn't know there was intended to be a default community. 

It might be worth a note somewhere in the documentation that you must specify a minimum set of fields at this time? This seems a potentially frustrating issue that anyone loading their own data is likely to hit (x3 in my case...).

**Comment by fenekku** [comment]
Yes, the datamodel still has to be evolved for sure. I am not sure of a good place to advertise how this is only the first jab... :smile_cat:

**Comment by dfdan** [comment]
I was thinking for now just a footnote on the current documentation, under the curl example  stating something like "note if you wish to insert more data, the above represents the minimum set of fields currently required".

Longer term, clear documentation of the datamodel / best-practice usage is going to be important since neither the JSONSchema nor the Marshmallow code can give a complete picture.

**Comment by fenekku** [comment]
Now that communities is out, this is not relevant anymore.
