### ISSUE TITLE
vocabularies: resource types - differentiate between depositable vs linkable

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-rdm-records#760]
It should be possible to differentiate between resource types that you can deposit in a repository vs which resource types that you can link to in the related identifers field.

**Comment by fenekku** [comment]
So... I will review each PR in good faith, but I am not sure I see the value in the premise of the solution. If the problem is that we need a different list of resource types (one for depositable and one for linkable resource types) well... why not make different lists? 

Have a vocabulary fixture for each (`linkable_resource_types.yaml` + `depositable_resource_types.yaml`)and then use those. That would require a change in invenio-rdm-records and invenio-app-rdm. Adding 30 or so resource types is less complex than cracking open 4 modules (all the way to invenio-records!) and adding custom code to address this 1 use case, no? I am probably missing something :sweat_smile:
