### ISSUE TITLE
pids: valid system-managed values accepted

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-records#761]
It is currently possible to create (and possibly update) a draft with a "system-managed" provider/client configuration, e.g. a "datacite" DOI with a prefix different from the one configured. The following service (and REST API) input is possible:

```python
def test_pid_creation_invalid_format_value_managed(
    running_app, es_clear, minimal_record
):
    superuser_identity = running_app.superuser_identity
    service = current_rdm_records.records_service

    doi = {
        # valid PID, but not with the configured managed prefix (i.e. 10.1234)
        "identifier": "10.5678/valid.doi",
        "provider": "datacite",
        "client": "datacite"
    }
    minimal_record["pids"] = {"doi": doi}

    # Create should fail with a validation error (see below)
    draft = service.create(superuser_identity, minimal_record)
    
    # In case we don't fail "hard" this should be an empty dict (see below)
    assert draft.to_dict()["pids"] == {
        "identifier": "10.5678/valid.doi",
        "provider": "datacite",
        "client": "datacite"
    }

    # Expected result
    assert draft.to_dict()["pids"] == {}
    assert draft.errors == [
        {'field': 'pids.doi', 'messages': [
            # Or a more user friendly error message?
            _('The "datacite" provider for "doi" is system-managed.')
        ]}
    ]
```

Thankfully, even though creation is possible, on publish there will be a failure, but for an unrelated reason (it will try to lookup the PID with value `10.5678/valid.doi`, and fail with `PIDNotExists`).

This issue also affects the OAI PID registration (since it makes it possible to submit OAI values, which of course don't make sense, since OAI PIDs are generated only locally by the instance).

### Proposed solution

- PIDs configurations with `system_managed=True`, should not accept user input at all (i.e. it shouldn't be possible to submit `provider=datacite` and also an `identiier=...` value)
- It should only be possible to reserve `system_managed=True` PIDs, in case one wants to know their value before publishing

**Comment by ppanero** [comment]
The issue refers to being able to create a pid (managed) with a different prefix than the configured one.
In the tests, this ill fail (i.e. create it properly) because we do not have a client set up and therefore this step of the validation is not executed https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/pids/providers/datacite.py#L239. Said call would check the prefix among other things at datacite api level https://github.com/inveniosoftware/datacite/blob/5ba45fcb2f4c460f6c5d563a9110edb77d532106/datacite/rest_client.py#L94.

We decided to not test that due to the complexity/security implications of adding a test case that requires 3rd party credentials. Options:
- Check manually an assume it wont change (hmmm  )
- Duplicate the validation to be 100% sure on our side... Im quite sure datacite would not allow us to register so at least the async task would fail?
- Add credentials to the tests

**Comment by tmorrell** [comment]
For testing an incorrect prefix, it should be fine to test with dummy credentials. The `check_doi` call will always happen before any interaction with DataCite and should fail out with a ValueError. It shouldn't matter that the credentials don't actually work.

**Comment by ppanero** [comment]
Fixed in the other PR:
- Made the DataCite provider a bit more strict, but consistent. I.e. it will not check itself for credentials or not, it will always make the corresponding calls. This means, the check_doi call will happen, if after the user calls e.g. `public_doi` it will fail. In my opinion, this is the desired behavior, because it means something is not configured.
- Tests at provider level for validation have been implemented.
- The test provided by alex on top is not valid on the new implementation. We want the datacite pids to have a specific format which means we do not allow the user to provide a custom value. Other providers are allowed to have this functionality.
